version: '3.2'

services:
  iris:
    build: 
      context: .
      dockerfile: Dockerfile
    restart: always

    container_name: iris-hl7qs

    ports:
    - "51785:51773"
    - "52785:52773"

    hostname: server-hl7qs

    volumes:
      - ./:/iris/app
